codecov:
  token: c82f3f4f-9bd2-42b4-ad38-f7d4bf9f507b
#  branch: master

ignore:
  - "Shared/Sources/Debug/Debug.swift"
  - "Tests"
  - "UITests"
  - "Example"
  - "Carthage"
  - "Pods"
  - "Module"
  - "Submodule"
