module: Fluidable

author: Gumob
author_url: http://gumob.com
github_url: https://github.com/gumob/Fluidable
copyright: 'Copyright © 2019 Gumob. All rights reserved.'

readme: "README.md"
documentation: "USAGE.md"

theme: fullwidth
# theme: "themes/fullwidth-ex"

xcodebuild_arguments:
  - -project
  - ../Fluidable.xcodeproj
  - -scheme
  - Fluidable

output: "docs"
min_acl: public
clean: true
skip_undocumented: false
hide_documentation_coverage: true
source_directory: Sources
umbrella_header: "Sources/Fluidable.h"

exclude:
  - Sources/Core/Proxy/FluidCompatible.swift
  - Sources/Core/Delegate/FluidNavigationDelegate.swift
  - Sources/Core/Delegate/FluidTransitionDelegate.swift
  - Sources/Core/Enumeration/FluidAnimationType.swift
  - Sources/Core/Enumeration/FluidInteractionType.swift
  - Sources/Core/Enumeration/FluidNavigationStyle.swift
  - Sources/Core/Enumeration/FluidTransitionStyle.swift
  - Sources/Core/Enumeration/FluidFrameDimension.swift
  - Sources/Core/Enumeration/FluidFrameStyle.swift
  - Sources/Core/Animator/Protocol/*.swift
  - Sources/Core/Animator/Implementation/*.swift
  - Sources/Core/Driver/Protocol/*.swift
  - Sources/Core/Driver/Implementation/*.swift
  - Sources/Core/Gesture/Protocol/FluidGestureDelegate.swift
  - Sources/Core/Gesture/Protocol/FluidGestureObservable.swift
  - Sources/Core/Gesture/Protocol/FluidScrollObservable.swift
  - Sources/Core/Gesture/Implementation/*.swift
  - Sources/Core/Parameter/Protocol/*.swift
  - Sources/Core/Parameter/Implementation/*.swift
  - Sources/Layout/*.swift
  - Sources/Helper/*.swift
  - Sources/Shared/*.swift
  - Sources/View/*.swift
  - Example/*
  - Tests/*
  - UITests/*

custom_categories:

  - name: Core
    children:
    - Fluidable
    - FluidResizable
    - UIApplicationDelegate

  - name: Delegate
    children:
    - FluidDelegate

    - FluidNavigationControllerDelegate
    - FluidNavigationSourceConfigurationDelegate
    - FluidNavigationDestinationConfigurationDelegate
    - FluidNavigationSourceActionDelegate
    - FluidNavigationDestinationActionDelegate

    - FluidViewControllerTransitioningDelegate
    - FluidTransitionSourceConfigurationDelegate
    - FluidTransitionDestinationConfigurationDelegate
    - FluidTransitionSourceActionDelegate
    - FluidTransitionDestinationActionDelegate

    - FluidResizableTransitionDelegate

  - name: Enumerations - Presentation Style
    children:
    - FluidPresentationStyle
    - FluidDrawerPosition
    - FluidSlideDirection

  - name: Enumerations - Transtion & Interaction
    children:
    - FluidProgressState

  - name: Struct - Transtion & Interaction
    children:
    - FluidGestureInfo
    - FluidGestureDirection
    - FluidGestureAxis
    - FluidInteractionBehavior

  - name: Struct - Frame and Style
    children:
    - FluidInitialFrameDimension
    - FluidFinalFrameDimension
    - FluidInitialFrameStyle
    - FluidFinalFrameStyle
    - FluidRoundCornerStyle
    - FluidBackgroundStyle

  - name: Transition - Custom Transition
    children:
      - FluidTransitionAnimatorCompatible
      - FluidTransitionAnimatorParameter

  - name: NavigationBar
    children:
      - FluidNavigationBar
      - FluidNavigationBarCompatible

  - name: Proxy
    children:
    - FluidProxy
    - FluidProxyCompatible

  - name: Type Aliases
    children:
    - FluidNavigationController
    - FluidSourceViewController
    - FluidDestinationViewController
    - FluidNavigationRootNavigationControllerDelegate
    - FluidNavigationSourceViewControllerDelegate
    - FluidNavigationDestinationViewControllerDelegate
    - FluidTransitionRootNavigationControllerDelegate
    - FluidTransitionSourceViewControllerDelegate
    - FluidTransitionDestinationViewControllerDelegate

  - name: Error
    children:
    - FluidError

  - name: Animator
    children:
    - FluidAnimatorCompatible
    - FluidAnimatorState
    - FluidAnimatorEasing

  - name: Animator - UIViewPropertyAnimator
    children:
    - FluidPropertyAnimator
    - UIViewAnimatingStateEx

  - name: Animator - Core Animation
    children:
    - FluidCoreAnimator
    - FluidCoreAnimatorTransitionType
    - FluidCoreAnimatorTransitionSubtype
    - FluidCoreAnimatorKeyCompatible
    - FluidCoreAnimatorKey
    - FluidCoreAnimatorPath
    - FluidCoreAnimatorError

  - name: Animator - Robert Penner's Easing
    children:
    - PennerEasing
    - PennerEasingType

  - name: Adaptive Layout - Protocols
    children:
    - AdaptiveAttribute
    - AdaptiveElement
    - AdaptiveInterface

  - name: Adaptive Layout - Attributes
    children:
    - SizeCategory
    - SizeClass
    - LayoutDirection
    - Idiom
    - Scale
    - DisplayGamut
    - ForceTouch

  - name: Adaptive Layout - Containers
    children:
    - AdaptiveBehavior
    - AdaptiveConstraintContainer
    - AdaptiveViewContainer

  - name: Adaptive Layout - Extensions
    children:
    - UITraitCollection
    - UIView+Adaptive
    - AdaptiveViewContainer

  - name: Extensions
    children:
    - CATransform3D
    - CGAffineTransform

  - name: Guide
    children:
    - USAGE
