coverage_service: cobertura_xml
xcodeproj: Fluidable.xcodeproj
scheme: Fluidable
source_directory: Sources/
output_directory: Reports/coverage
ignore:
  # - Sources/Core/Enumeration/FluidConst.swift
  # - Sources/Core/Enumeration/FluidCoreAnimatorOption.swift
  - Sources/Helper/Extension/VectorMath.swift
  - Sources/Helper/AdaptiveLayout/*/*.swift
  - Sources/Shared/*.swift
  - Tests/*
  - UITests/*
  - Example/*
  - Carthage/*
  - Pods/*
  - Module/*
  - Submodule/*
