# at v0.6.0
disabled_rules:
  - identifier_name
  - shorthand_operator
  - trailing_whitespace
  - todo
  - large_tuple
  - function_parameter_count
  - trailing_comma

line_length:
  warning: 512
  error : 1024
  ignores_comments: true
file_length:
  warning: 512
  error : 1024
  ignores_comments: true
function_body_length:
  warning: 256
  error : 512
  ignores_comments: true
shorthand_operator: warning
cyclomatic_complexity:
  warning: 20
  error: 40

identifier_name:
  excluded:
    - id
    - ok

excluded:
  - .bundle
  - fastlane
  - Carthage
  - Tests
  - UITests
  - Example
