# at v0.6.0
disabled_rules:
  - identifier_name
  - shorthand_operator
  - trailing_whitespace
  - todo
  - large_tuple

line_length: 480
function_body_length: 100
shorthand_operator: warning
cyclomatic_complexity:
  warning: 20
  error: 40

identifier_name:
  excluded:
    - id
    - ok

excluded:
  - .bundle
  - fastlane
  - Carthage
  - Tests
  - UITests
  - Example
