language: swift
os: osx
osx_image: xcode11.5

xcode_project: Fluidable.xcodeproj
xcode_scheme: Fluidable

branches:
  only:
    - master
    - develop
#    - "/^v?[0-9\\.]+/"

cache:
  directories:
    - Pods
    - Carthage

env:
  global:
    - secure: IsSPmEYizg0SVZoWqO8JnSgCKlNSBLIFs+XZjOCjb12Z+YToMS3tmo+EYrmaKNJRMrvJEFyRlgyxlyEQGHc57eFGzZAjLGsiiIu++xY7AzDALC+CDG3w2daNF+pWXX58145Wj5CpOrkauF+DHUMYCQWa3g4JGoMmP001fjKlF+9TUF7K017Ae6awVu3YFJqvO2KuCEpe3J7b6Ii0hjUEnHMzHgK+ZFwGbc8QXz21AGO5YXT3+6zxaLB4TdEyazRC/QxaDBpmSE8k4RMeOXBTbwhpJhWbrDuGGJWw46yO006d7YdU8+fkf6hSBswN5YGbOga8dwRB4vVilJ6P8iiUV9QL4C1BxU8jFBkil563o5mbl6MZrEjXPQuvwyB9xSf6LGjYyVXrAVj6nIar+QcfwSIqn2520qYxrYo5CAaZ/9ozmRg4v4fbnA6m2fEW1lI7USQGKcByit6ZGxQQ6YwdS0mw83fvGotxptgc/by2e7b1O64i2BWEh/5fHt/B3+6j7HkzDHvMKoOgFoNKMbrtEit9R7Dnrdsgd0awVnQzY0EdWdmYGH1A9h9pHJhmEoQq2S1X2tOf1WC0y67dY1FIMMk+27dn7ZBTsmKKdQf/RCYNSxhzHFjyaMr5nBkqxf4UV73l0JMT6Nhi5KrSCIYnOUA9peEETXmo9oBssPuVHSk=
    - CODE_SIGN_OPTION='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"'

matrix:
  include:
    - env: DESTINATION="OS=13.5,name=iPhone 11 Pro"         XCODE_TEST="YES" COVERAGE="YES" CODECOV_FLAG="ios13"
    - env: DESTINATION="OS=12.4,name=iPhone X"              XCODE_TEST="YES" COVERAGE="NO"  CODECOV_FLAG="ios12"
    - env: DESTINATION="OS=11.4,name=iPhone 7"              XCODE_TEST="YES" COVERAGE="NO"  CODECOV_FLAG="ios11"
    #- env: DESTINATION="OS=10.3.1,name=iPhone 6"     XCODE_TEST="YES" COVERAGE="NO"  CODECOV_FLAG="ios10"
    - env: DESTINATION="OS=13.5,name= iPad Pro (12.9-inch)" XCODE_TEST="YES" COVERAGE="YES" CODECOV_FLAG="ios13"
    - env: DESTINATION="OS=12.4,name=iPad Air 2"            XCODE_TEST="YES" COVERAGE="NO"  CODECOV_FLAG="ios12"
    - env: DESTINATION="OS=11.4,name=iPad Air 2"            XCODE_TEST="YES" COVERAGE="NO"  CODECOV_FLAG="ios11"
    #- env: DESTINATION="OS=10.3.1,name=iPhone 6"     XCODE_TEST="YES" COVERAGE="NO"  CODECOV_FLAG="ios10"
    #    - env: CARTHAGE_TEST="YES"
    - env: SWIFT_LINT="YES"
    - env: POD_LINT="YES"

before_install:
  - if [ "$XCODE_TEST" == "YES" ]; then
    gem install xcpretty --no-document --quiet;
    fi
  - if [ "$CARTHAGE_TEST" = "YES" ] || [ "$XCODE_TEST" = "YES" ]; then
    brew update;
    brew outdated carthage || brew upgrade carthage;
    carthage bootstrap --platform iOS --no-use-binaries --cache-builds;
    fi
  - if [ "$POD_LINT" == "YES" ]; then
    gem install cocoapods --pre --no-document --quiet;
    pod repo update;
    fi

install:
  - if [ "$SWIFT_LINT" == "YES" ]; then
    ./install-swiftlint.sh;
    fi

script:
  - set -o pipefail;

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    swift -version;
    xcrun simctl list;
    xcodebuild -version;
    xcodebuild -showsdks;
    xcodebuild -list;
    fi

  - if [ "$XCODE_TEST" == "YES" ]; then
    xcodebuild clean test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$DESTINATION" -enableCodeCoverage $COVERAGE | xcpretty -c;
    fi
  - if [ "$CARTHAGE_TEST" == "YES" ]; then
    carthage build --no-skip-current --platform iOS;
    fi
  - if [ "$SWIFT_LINT" == "YES" ]; then
    swiftlint lint;
    fi
  - if [ "$POD_LINT" == "YES" ]; then
    pod lib lint;
    fi

after_success:
  - if [ "$COVERAGE" == "YES" ]; then
    bash <(curl -s https://codecov.io/bash) -J 'Fluidable' -cF "$CODECOV_FLAG" -y ".codecov.yml";
    fi

# after_failure:
#   - if [ "$CARTHAGE_TEST" == "YES" ]; then
#     cat $TMPDIR/carthage-*.log | true
#     cat /var/log/system.log
#     fi
#   - if [ "$XCODE_TEST" == "YES" ]; then
#     find $HOME/Library/Developer/Xcode/DerivedData/Fluidable-*/Logs/ -name '*.log' -print0 | xargs -0 cat
#     cat /var/log/system.log
#     fi

# notifications:
#   email: false
#   slack:
#     secure: Q7z8piC9uUmPQHmjov051jM+j4nKF5i5iaO/ZXm+JZlC7nddmHQlMZFJ75ZFuMTAnzHWPKJvBnPW4upG6BALNrQZOexqjUeyUVy3fR5S9eM0+uBr69+AYUH1jFSlXTmhHqTepZDKtP1pNnexrO31Rt5l/rH1BkGGOispeOZdY4quxj5QHRFQle3cMx4qdl93TCVpKmATbtpSz8kMdsda5gO4lsNW2LiMKPWwapXME5E7g2sO/4Qg17Mbzx16pWFILMHBHPHIcYEaFwithgfb3ALIx1IqDzmj1iZ7XoxsC+D6b3vr8eMv5EFW3MgVE1nc8yTjgKRJ/qZ/WGE0Z+jmhLyFCRxvX0cCui6a3RoFEXRniCAWPq58PK1JCjB8vhqJ18YzA7ctzf8k+kava4KTFrNJ7GMITuuEh4GrURRCeulKuVj+AQJQh40HdbOZ56PtR7uFQpCY+UL8lzWSAmnNEydf+UTHs/FDYqT9GB4qVahmmjmnD29N0OHFdjbAzdkn1+RkAI09Z2Kr7YjlSk51vbR0hNRvtMPy3r5qEb6g5gu02DACCDcVBD/Atdpmv2ISqez3STSSA3xcTC8OOtGNM/WTQw1fKBjSs5stsALnGYmtFSbPiKKo6CKaryOedtnQbVYX8YU6nKcwaEKw1X51JxYoivt+LXXsHsZcDVJ4cbg=
