language: swift
os: osx
osx_image: xcode10.2

xcode_project: Fluidable.xcodeproj
xcode_scheme: Fluidable

branches:
  only:
    - master
    - develop
#    - "/^v?[0-9\\.]+/"

cache:
  directories:
    - Pods
    - Carthage

env:
  global:
    - secure: IsSPmEYizg0SVZoWqO8JnSgCKlNSBLIFs+XZjOCjb12Z+YToMS3tmo+EYrmaKNJRMrvJEFyRlgyxlyEQGHc57eFGzZAjLGsiiIu++xY7AzDALC+CDG3w2daNF+pWXX58145Wj5CpOrkauF+DHUMYCQWa3g4JGoMmP001fjKlF+9TUF7K017Ae6awVu3YFJqvO2KuCEpe3J7b6Ii0hjUEnHMzHgK+ZFwGbc8QXz21AGO5YXT3+6zxaLB4TdEyazRC/QxaDBpmSE8k4RMeOXBTbwhpJhWbrDuGGJWw46yO006d7YdU8+fkf6hSBswN5YGbOga8dwRB4vVilJ6P8iiUV9QL4C1BxU8jFBkil563o5mbl6MZrEjXPQuvwyB9xSf6LGjYyVXrAVj6nIar+QcfwSIqn2520qYxrYo5CAaZ/9ozmRg4v4fbnA6m2fEW1lI7USQGKcByit6ZGxQQ6YwdS0mw83fvGotxptgc/by2e7b1O64i2BWEh/5fHt/B3+6j7HkzDHvMKoOgFoNKMbrtEit9R7Dnrdsgd0awVnQzY0EdWdmYGH1A9h9pHJhmEoQq2S1X2tOf1WC0y67dY1FIMMk+27dn7ZBTsmKKdQf/RCYNSxhzHFjyaMr5nBkqxf4UV73l0JMT6Nhi5KrSCIYnOUA9peEETXmo9oBssPuVHSk=
    - CODE_SIGN_OPTION='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"'

matrix:
  include:
    - env: XCODE_TEST="YES" RUNTIME="iOS 12.2" DEVICE="iPhone XS Max" COVERAGE="YES" CODECOV_FLAG="ios12"
    - env: XCODE_TEST="YES" RUNTIME="iOS 11.4" DEVICE="iPhone 8 Plus" COVERAGE="NO"
    - env: XCODE_TEST="YES" RUNTIME="iOS 10.3" DEVICE="iPhone 7"      COVERAGE="NO"
#    - env: CARTHAGE_TEST="YES"
    - env: SWIFT_LINT="YES"
    - env: POD_LINT="YES"

before_install:
  - if [ "$POD_LINT" == "YES" ]; then
    gem install cocoapods --pre --no-document --quiet;
    fi
  - if [ "$XCODE_TEST" == "YES" ]; then
    gem install xcpretty -N --no-document --quiet;
    fi
  - if [ "$CARTHAGE_TEST" = "YES" ] || [ "$XCODE_TEST" = "YES" ]; then
    brew update;
    brew outdated carthage || brew upgrade carthage;
    fi
  - if [ "$CARTHAGE_TEST" = "YES" ] || [ "$XCODE_TEST" = "YES" ]; then
    carthage bootstrap --platform iOS --no-use-binaries --cache-builds;
    fi
#  - swift -version;
#  - xcrun simctl list;
#  - xcodebuild -version;
#  - xcodebuild -showsdks;
#  - xcodebuild -list;

install:
  - if [ "$SWIFT_LINT" == "YES" ]; then
    ./install-swiftlint.sh;
    fi

before_script:
  - if [ "$XCODE_TEST" == "YES" ]; then
    DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g");
    RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g");
    DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID);
    xcrun simctl boot $DESTINATION_ID;
    fi

script:
  - set -o pipefail;
  - if [ "$XCODE_TEST" == "YES" ]; then
    xcodebuild clean test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "id=$DESTINATION_ID" -enableCodeCoverage $COVERAGE | xcpretty -c;
    fi
  - if [ "$CARTHAGE_TEST" == "YES" ]; then
    carthage build --no-skip-current --platform iOS;
    fi
  - if [ "$POD_LINT" == "YES" ]; then
    pod lib lint;
    fi
  - if [ "$SWIFT_LINT" == "YES" ]; then
    swiftlint lint;
    fi

after_success:
  - if [ "$COVERAGE" == "YES" ]; then
    bash <(curl -s https://codecov.io/bash) -J 'Fluidable' -cF "$CODECOV_FLAG" -y ".codecov.yml";
    fi

after_failure:
  - if [ "$CARTHAGE_TEST" == "YES" ]; then
    cat $TMPDIR/carthage-*.log | true
    cat /var/log/system.log
    fi
  - if [ "$XCODE_TEST" == "YES" ]; then
    find $HOME/Library/Developer/Xcode/DerivedData/Fluidable-*/Logs/ -name '*.log' -print0 | xargs -0 cat
    cat /var/log/system.log
    fi

notifications:
  email: false
